# Generated by Django 2.1 on 2020-05-28 01:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('diversity_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectfingerprint',
            name='fp',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Atom Pair', 'Atom Pair')], max_length=9, verbose_name='Fingerprint'),
        ),
    ]
