# Generated by Django 2.1 on 2020-05-28 01:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_space', '0004_auto_20200127_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptors',
            name='pca_fp',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Atom Pairs', 'Atom Pairs')], max_length=10, verbose_name='Fingerprint'),
        ),
        migrations.AlterField(
            model_name='descriptors',
            name='tsne_fp',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Atom Pairs', 'Atom Pairs')], max_length=10, verbose_name='Fingerprint'),
        ),
    ]
