# Generated by Django 2.1 on 2022-10-17 00:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_space', '0005_auto_20200528_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptors',
            name='pca_pp',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Physicochemical properties', 'Physicochemical properties')], max_length=26, verbose_name='Physicochemical'),
        ),
        migrations.AlterField(
            model_name='descriptors',
            name='tsne_pp',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Physicochemical properties', 'Physicochemical properties')], max_length=26, verbose_name='Physicochemical'),
        ),
    ]
